spring:
  h2:
    console:
      enabled: true

  sql:
    init:
      encoding: UTF-8

  datasources:
    url: jdbc:h2:mem:testdb

  jpa:
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 562744272388-nqlach6s86nctf2pncjq00h3mevpij4i.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
server:
  port: 443
  ssl:
    enabled: true
    key-store: classpath:bootsecurity.p12
    key-store-password: 950214
    key-store-type: PKCS12
    key-alias: bootsecurity
  error:
    include-exception: true # 오류 응답에 exception 내용을 포함할지 여부
    include-stacktrace: always # 오류 응답에 stacktrace 내용을 포함할지 여부
  whitelabel:
    enalbed: false # 브라우저 요청에 대해 서버 오류시 기본으로 노출할 페이지를 사용할지 여부
  servlet:
    encoding:
      force: true

